# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://u17283818.github.io/
baseurl: /sustain/
title: Khakhu Ramakuela
author: Khakhu Ramakuela
description: CV
email: kramakuela@gmail.com
github: https://u17283818.github.io./
twitter: khakhu_r
linkedin: www.linkedin.com/in/khakhu-ramakuela-94a1aa108
stackoverflow: https://stackoverflow.com/users/10471131/khakhu-ramakuela
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
